apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: n8n-daily
  namespace: velero
spec:
  schedule: "30 3 * * *"
  useOwnerReferencesInBackup: false
  template:
    includedNamespaces:
      - n8n
    snapshotMoveData: true
    ttl: 336h
