apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n.local.khider.fr-cert
  namespace: n8n
spec:
  secretName: n8n-cert
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - n8n.local.khider.fr
