---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBul+cCG/c9NfMJ7UUmBa+mambGfs+hdspmleww+CEsLQkpiumWkOwLU/Y0RC50a7RD2K8jj7jaiVC+258x89y6xiaXH6C5MzOdW9iovbhO3YnOSWKU4D+5sgFpoFs9a0EBFY8ugLiupdddue22iqrAC6eoYpGlnP+Pkhqm/eHvy/r48W1l4UoVtJJfbJcrAPZ1YmUBaSc1xJge092PGW1hXtzYhIfYbisjlfCF2MiHTc1Z7d0Q3IEPHqrp5aTgmVIB6PPXv7X2g0CEzfbhjM8bYMoAYuFiToI7AFhX+PRif8lEBz4e1wD68AXGVVpHhkaQaumhVRkzCwT/F6QNlbq8LiBWhwJSO+kO4kntDnNqlj7BpUGExnf5p+LUvdAWXFTQT0saav7mrFQcSDmF/Q4gb+dI250S5Tf3J1m/fXbI0g559gladCZgZkqdTcYMIvP3Hw4VEFG18EiZuySJ5oigeB3MYNs5xu3tprjywLYZpL1cdwwmYDpgGTirLdlrxM4ZdvKowEpmdn+oz8DIIngReYnZa97Y93vuarYmY4n10Zpiiaj1L1hzGckbfIWNr7uTubprmWDS5xHXmFhC85owiz7FFHkH0JCkRxFZRDusseYxBIZ7BDtf2pnJ9vuwJlvTCmckcpD0Th947eqJI74PFgO4fwWJziVfXt5m1+muU+51Ycr0Qvi+FJtKdIO8L8KIlbAgHFHoPd20e0OFEr9K449JyaS2gIkyIK4WAbptyoo0XLrAgG3VGDXIdUFlvwTtZfk7Tg==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
