apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - cloudflare-sealed-secret.yaml
  - cert-manager-cloudflare-issuer.yaml
