---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-r2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBx7PVZePEPA+4bC1mz4GNfwdR+iDGZ1UuRAgIvsVwzuStQqZpzcmc2nJceZ2FIFBC7oCEKQs7j6PlBoSjEaPqHCA+GuaXUsZxmMtvjBgA/PDYcMRI6pdA1Yb3MRP8+tCt3SGWefhyHjJMlEuA+WOOQTfSbhEYw67Vo94Yj/nDXsbGeHEyG9iKIs9MBg50AIobcBsno4aR5+KFRN56EbWgG26C/o8WxNkJv2/Fjd2bthIzR0bTv9YKwvpTAJw3QTQWt9Et4cB6YNm/SIAXw8IIUSSdc+yQqFgJP/OcmQsIhsZpeNQX2JxMUnD4jDLo3NbJCCK3HLQPwmjyxP701rTq9y+U6+n3TUCWKb71Kr4NbYc1XhiAGQGR0UBoETxzWbI+WO/Y/cwHS+O3lqmqIMNkv2yMR2atbo2DtcGGIuqZagBvcXgiB1ukmu6x8xttsWb65TNYhZY2Lv57tXtYHcW1/TfM5fbu1hBcYKiB+t+O1qk/Rx8up3qQPdkn+W3Nwg3TjxCNOavsCEqjyNrmxRUvZZBVXbcjmYe/5+jWXy+bV7ObHYceH8qsbikdvEqC24AuHYc3gMWa2iQDE0ft6OUstfgcfNJgB9jYc01Kpd1H0Lt5ztbAahYWty/3y0tJIhLSzKoZzapnAhZzxYirfitrHgHvysGeuSxKORf1LBZoyVwneADBLPhgcFzPPNlt63t8ze05twKO7DRaa7RlhPF9uln73WIhgf37VWyIa7dwPKebIvEI6raMkSIzkfveEEpGx9ugYkBSFZfwZ2bkHJErfGuYkAu9PbtbRkoOknL3LjgQ3eKpHGA02oeoXaVfkgfD8DZNyPC+zqszrmW2l9YC3Xrg30dPtxxroeyJTDKg2W0cQq4VSjZuqy2pyRpQbgb2RPupVvHje8g==
  template:
    metadata:
      name: velero-r2-credentials
      namespace: velero
