---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pushover-credentials
  namespace: monitoring
spec:
  encryptedData:
    api-token: AgDGwSmaB5GxEAgQuF1N2QxNsahbD6kT38FwhGwwr0NlrVOgWBXOSy9CyE89iJk3wB2GJkp2b4/b1RzeCSbS2dJJjNiKTpiB05TQPBcKzgm0+e+DcMApq1GRAWiNdaK+3jbu9MsTuk5CmtUj7XqRco1hv/YSmUFW0vTFrY4EDK4x78EB7NH7k9mrUPNF9o+u+5b5XGw+UpZTGnCYmdfbkf8u4A7N4I+AlsdkLUq3RBZFqvs14EAi9BgA4i+wGiyo2h6MJVl4rdGzk0YRAs8OVqPb+OnfLOxGbs1HkWlB/OeaRoYjYNTybEv95Z57ABW7WIk7zbPIZcD5FiZTYdiAaSzCADZSoFvjDeKJT1J5k2sVPOhJSSbLOUE8/EFB0sPIQjt27v7g5b8GncHXQoXOSdbOQqB+GEgPwO+FIB58Kid9RdQ3MvZviqsXThmWc0mp2ubOtpbs+OlwT0lYMrREU4VmL2KCmpuqFiPxYtcylCgJq/UAiqypG455PkeFAj+K5xgWJq0XStVlZKnfTi/QfmUayG9OjZKDaF/weUM8zwj9VeIYIooWrW+TGOd5Mx0Doq5l2LjCSAG9Qx0QJG7XYNVvJSU0mdSmWMYC+jOPf14sBkObfVhjvz5VSNJCUseUxJ1Y7DxM44Q1JABHcGTUycI9YbtmZhB6ZRC+WmmYHCUa+5t6fHkaehtQktNW2hRZ/L12RczQjfipM9+zr23VVNsNcDNW9sLqMw1BbiwsPZE=
    user-key: AgAmOHddHYIsfIh79KFR8PsclZVDUMMcFTIRkYp04OcZK83jdM3HI2ESTKiD5ywzHnQdDzcT/HJs0xTuKBv7GHdyPJ9FCs5FhfsS7Tz3tMJlfqGcpmhqWprgXmjDF1BfhzFIFcPewjP/5mmLhD7ADC+6MkevHFmX27szVtUrcZQ9W7anQMl4o8U3AWpUcLzq6qNaJ2edcYlVfBu2b8pmXLUabWNzSlQFydDIi37OQm6fRbmTrUQhVWb+fvY2EZHqzPxjkWlXdwIXwPkGY6VUNZIFczrAqBTVxQWJF3Auf/kvtFeZSkg8gs0aXvKNTR3AQJrRb6SOa5M5eK3fJNXa/AyPlFDOGu1tJpBwW8MSoymTOXv6YY18hgfzeqd1dcpwnnzlKxzSPPxw9+E6Tv5uLpKP6JYZIRxStLl/SSEE9UjfsVuoa2owtVttsiu1CmqiwIcPzidECQbNYqRKFbi9RSOPffjKACNSp2kxuNOg3FH4J1jVwDoJ/YL9KqqB6/vFbXSZ/wFpr/VLDyP0xsyN6MwSBpGXiE67cS7oQjW+7oes28zdEvXwfxU6EvXHZ0sAZ6xf6kT6YqmPwMQ2aUH08pvzrPvWj6xKwGnJfk+rBKJL1G9tCCmp2v6lGR6kE34iJOtCKhTlLsdSKCqjOOLNVoUxRGTq9YUh8yss2OpJxnUfvxO8no5eNCBu6TS1qWErzfEsEKOCkdBlNugJuXeJE6MLQbUkvEl0in//7PcZXWo=
  template:
    metadata:
      name: pushover-credentials
      namespace: monitoring
    type: Opaque
