---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pushover-credentials
  namespace: monitoring
spec:
  encryptedData:
    api-token: AgDIxq+08/JjF3n1vDHDOOYU9fdAyDF/3fIWivQUo21T2ySWRfrpj6D2jBALHWbo2I8eAxQq6mq+VWPrxnAOIIGCJZr/TK5x2taBx5SILlQ841IyWmJ+L2xnsP9IIn3AZVXOEoxqhQ+T9ZvGLsxskfA7sA/fZqZT3Uug4AmfIxAw/dQn8zlpnBDRMlTnPTifoWmVRXBTGYGxixvc2I9wf/TCycddd11cmWggqN5ly0HRPNcOgjCbIGSbPyu0m8UEXDIIbo2ePy4mH9GMa6Xowob/bPGSH32Kusavd3KDqQfyh9cNwx+lm0yJrULEjRU5km6cxIa8MVadrJcnjrGim6ezeTuJMm3UyZfp2V5I7HrwoDEA+/pgBAZQkI6eLcwHh6QmuSEturEC7ztDn0493ZrMYoZduxGxUazCmNkZ0RZDJx11gbz9fOykXLeu3wdopE44NBUyqcALkrUdB7dy3F9sok/zD4AGrBd8RE7QfeQR4gXqpa/HI362UNHxM6Nb5hW59d8f2DyOWuPGDe27oVdnpGbN06eHUuNO4hMcKlhAzWwIgUIcpne/offLO+dV76rOXITYAMcqnzJhbKy+8QqYhdN7ZuMD5F2FxEZCnxEfZ6+BR6nvMYQyhQBnDLWbyoN8J79R1oni+qSdIdCaBKT8HitBoW+DjB9+dUFRHpxlPPH/EVbjNofcDWjgNNbn0DdkTcB1i8fk/9cAf709bb0WDpy1VombQiXldVx/Wtk=
    user-key: AgBR83GDbDOK+uk08H25k1yrPzsctqO8B9xCRVzD5lREM/1T5zO5WeMuB4imlCI0AKofuJ1raPdRGxTjxAFjTcT0YZJJQ+NPbS9sPKTK2X/YJ5+M4XAB8LEYZ1QdoYlVadi8Ep+V4RUFjbVXHsWwTpD+I45rJ+v2iSyZM0hnrIEjeVZpo7fhifvBseu6rcZnRS6fm6F83eiQ8YGR97PoI6PkFSkSobXFTZI6Ir8bjMTTD5GDbs/697Hxg1nadDKNDsBQNo1m2ND7I2AXjrLqV2PY8yevyin8wz+joJHOZBmKwVBbXkD+sL/lv2CjKG5JLpymmGD19EKTx6fhW9qUxP8BVPV3QnJqZs+aDD5BPOJSkN0iY3RACjwOuw9mUyijXmTpWytbfbGsxps6/EWk7QVs8HTYrF5c5siqQ1oIvo8QuK83TpRanK86so5NoMN+9azbQpMXW4KeUwyh7jLu0V2ERe/Wj1cqTQ9XrZeVOVt4hHDb1/GZkXWjUcj2lHqApXu6Fiia/lqyR26+n8bSqqMmtLExS6HZcnTE+/MR9iRudBrVrcf75+CFLqLYqsP3+OXM4II1VsfR5wk6o7rwpnsY2MzLEBwfiAaZ0UdeWKSe3Sy2ANijHCnnTbPbXAvKqrsvCmYdHyi+AKer0z/MDXKR/4hxMebLl4eiQHR2UcjRULozHsG5LO4tBJ7aR7GTV0vSySRAuHW2U5uEGPEuq08PZOqoCc6h/nTuh1SpfIk=
  template:
    metadata:
      name: pushover-credentials
      namespace: monitoring
    type: Opaque
