apiVersion: v2
name: nextcloud
version: 9.0.6
# renovate: image=docker.io/library/nextcloud
appVersion: 33.0.3
description: A file sharing server that puts the control and security of your own data back into your hands.
dependencies: []
