---
- name: Ensure target directory exists
  ansible.builtin.file:
    path: "{{ base_dir }}/{{ item }}"
    state: directory
    mode: '0755'

- name: Check for existing compose file on remote host
  ansible.builtin.find:
    paths: "{{ base_dir }}/{{ item }}"
    patterns: 
      - "compose.yaml"
      - "compose.yml"
      - "docker-compose.yaml"
      - "docker-compose.yml"
  register: remote_file

- name: Set target filename fact
  ansible.builtin.set_fact:
    target_filename: "{{ remote_file.files[0].path | basename if remote_file.matched > 0 else 'docker-compose.yaml' }}"

- name: Copy Git compose file to remote host
  ansible.builtin.copy:
    src: "{{ repo_dir }}/{{ item }}/docker-compose.yaml"
    dest: "{{ base_dir }}/{{ item }}/{{ target_filename }}"
    mode: '0644'

- name: Run Docker Compose Up
  community.docker.docker_compose_v2:
    project_src: "{{ base_dir }}/{{ item }}"
    files:
      - "{{ target_filename }}"
    docker_cli: /usr/local/bin/docker
    state: present
