apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - backup-storage-class.yaml
  - sealed-secret.yaml
  - node-agent-config.yaml
  - helm-release.yaml
